
#
# This LookML file was generated by AtScale on 2025-02-05T16:42:29.271238408Z
#
# AtScale version: 2024.11.1
# Catalog: 10TB SF_main

connection: "se_looker"
label: "10TB SF_main"


include: "/views/10TB_SF_main/TPCDS-10TB.view.lkml"


explore: TPCDS_10TB {
  label: "TPCDS-10TB"
}

